// 模拟数据
module.exports = {
  // 拼团中数据
  groupBuyingData: [
    {
      id: 1,
      title: '万达广场停车月卡拼团',
      type: 'group',
      date: '05/07 19:30',
      endDate: '05/09 20:30',
      people: 28,
      tag: '拼团',
      styleIndex: 0,
      isExpired: false,
      authorId: 1,
      location: '万达广场停车场',
      description: '万达广场地下停车场月卡拼团活动，拼满40个月即可享受优惠价格299元/月，原价399元/月。名额有限，先到先得。',
      targetMonths: '40',
      groupPrice: '299',
      originalPrice: '399',
    },
    {
      id: 2,
      title: '银泰中心停车月卡',
      type: 'group',
      date: '05/04 12:30',
      endDate: '05/13 22:00',
      people: 14,
      tag: '拼团',
      styleIndex: 3,
      isExpired: true,
    },
    {
      id: 3,
      title: '华强北商圈停车优惠',
      type: 'group',
      date: '05/10 18:00',
      endDate: '05/15 22:00',
      people: 32,
      tag: '拼团',
      styleIndex: 1,
      isExpired: false,
    },
    {
      id: 4,
      title: 'KK ONE购物中心月卡',
      type: 'group',
      date: '05/11 14:00',
      endDate: '05/12 20:00',
      people: 16,
      tag: '拼团',
      styleIndex: 2,
      isExpired: true,
    },
    {
      id: 5,
      title: '海岸城地下停车场',
      type: 'group',
      date: '05/13 09:00',
      endDate: '05/25 18:00',
      people: 24,
      tag: '拼团',
      styleIndex: 4,
      isExpired: false,
    },
    {
      id: 6,
      title: '深业上城停车月卡',
      type: 'group',
      date: '05/08 06:00',
      endDate: '05/30 22:00',
      people: 45,
      tag: '拼团',
      styleIndex: 5,
      isExpired: false,
    },
    {
      id: 7,
      title: '益田假日广场拼团',
      type: 'group',
      date: '05/18 19:00',
      endDate: '05/28 23:00',
      people: 89,
      tag: '拼团',
      styleIndex: 6,
      isExpired: false,
    },
  ],

  // 月卡转让数据
  transferData: [
    {
      id: 11,
      title: 'KK ONE停车月卡转让',
      description: '剩余20天，因工作调动急需转让，价格可议。月卡可正常使用，位置方便，地下停车场，24小时开放。',
      price: '150',
      location: '罗湖区',
      time: '30分钟前',
      imageStyle: 2,
      type: 'transfer',
      date: '05/14 10:00',
      endDate: '06/05 23:59',
      people: 1,
      tag: '转让',
      styleIndex: 2,
      publisher: {
        name: '张先生',
        wechat: 'zhang2024',
        phone: '138****5678',
      },
      details: {
        '有效期至': '2026-06-05',
        '原价': '¥299/月',
        '剩余天数': '20天',
        '停车场名称': 'KK ONE购物中心地下停车场',
        '车位类型': '固定车位',
      },
      images: ['img1', 'img2', 'img3'],
    },
    {
      id: 12,
      title: '海岸城地下车库月卡',
      description: '还有一个月到期，8折转让，先到先得。停车位置好，进出方便，安全有保障。',
      price: '200',
      location: '南山区',
      time: '1小时前',
      imageStyle: 4,
      type: 'transfer',
      date: '05/14 09:00',
      endDate: '06/14 23:59',
      people: 1,
      tag: '转让',
      styleIndex: 4,
      publisher: {
        name: '李小姐',
        wechat: 'lixiaojie88',
        phone: '139****1234',
      },
      details: {
        '有效期至': '2026-06-14',
        '原价': '¥250/月',
        '剩余天数': '30天',
        '停车场名称': '海岸城地下停车场',
        '车位类型': '临时车位',
      },
      images: ['img1', 'img2'],
    },
    {
      id: 13,
      title: '万象城停车月卡转让',
      description: '本月刚办理，因出差转让，价格优惠。几乎全新，可使用一整月。',
      price: '180',
      location: '罗湖区',
      time: '3小时前',
      imageStyle: 0,
      type: 'transfer',
      date: '05/14 06:00',
      endDate: '06/10 23:59',
      people: 1,
      tag: '转让',
      styleIndex: 0,
      publisher: {
        name: '王生',
        wechat: 'wang_parking',
      },
      details: {
        '有效期至': '2026-06-10',
        '原价': '¥280/月',
        '剩余天数': '27天',
        '停车场名称': '万象城购物中心停车场',
      },
      images: ['img1'],
    },
  ],

  // 闲置二手数据
  secondHandData: [
    {
      id: 21,
      title: '九成新跑步机转让',
      description: '因搬家急售，品牌跑步机，功能完好，使用半年。跑步机品牌为乔山，型号T900，原价6800元。功能齐全，带有蓝牙音箱、心率监测等功能。平时保养良好，9成新。',
      price: '800',
      location: '南山区',
      time: '2小时前',
      imageStyle: 0,
      type: 'secondhand',
      authorId: 1,
      publisher: {
        name: '运动达人小刘',
        wechat: 'liuxiaoming123',
        phone: '137****9999',
      },
      details: {
        '品牌': '乔山',
        '型号': 'T900',
        '购买时间': '2025年11月',
        '使用时长': '半年',
        '成色': '9成新',
        '原价': '¥6800',
      },
      images: ['img1', 'img2', 'img3', 'img4'],
    },
    {
      id: 22,
      title: '闲置健身器材处理',
      description: '哑铃、瑜伽垫、弹力带等，9成新。包括一对10kg哑铃、一对5kg哑铃、瑜伽垫2张、弹力带3条，全套打包出售。',
      price: '200',
      location: '福田区',
      time: '5小时前',
      imageStyle: 1,
      type: 'secondhand',
      publisher: {
        name: '健身小白',
        wechat: 'fitness_beginner',
      },
      details: {
        '物品清单': '哑铃4个、瑜伽垫2张、弹力带3条',
        '购买时间': '2024年6月',
        '使用时长': '1年半',
        '成色': '9成新',
      },
      images: ['img1', 'img2'],
    },
    {
      id: 23,
      title: '自行车出售',
      description: '骑行爱好者出售，变速自行车，保养良好。美利达公爵600，27速变速系统，铝合金车架，适合日常通勤和周末骑行。',
      price: '1200',
      location: '罗湖区',
      time: '1天前',
      imageStyle: 2,
      type: 'secondhand',
      publisher: {
        name: '骑行者老王',
        wechat: 'bike_lover_wang',
        phone: '135****7777',
      },
      details: {
        '品牌': '美利达',
        '型号': '公爵600',
        '变速': '27速',
        '车架材质': '铝合金',
        '购买时间': '2024年3月',
        '原价': '¥2800',
      },
      images: ['img1', 'img2', 'img3'],
    },
  ],

  // 招聘信息数据
  jobData: [
    {
      id: 31,
      title: '招聘健身教练',
      description: '要求有健身教练资格证，2年以上经验，薪资面议。我们是一家位于南山区的高端健身会所，环境优越，会员素质高。现招聘全职健身教练，要求形象好、责任心强、有团队精神。',
      category: '全职',
      location: '南山区',
      time: '1小时前',
      imageStyle: 4,
      type: 'job',
      price: '8000-15000',
      authorId: 1,
      publisher: {
        name: '力美健身会所',
        wechat: 'limei_gym_hr',
        phone: '0755-8888****',
      },
      details: {
        '岗位': '健身教练',
        '工作类型': '全职',
        '薪资': '8000-15000元/月 + 提成',
        '要求': '健身教练资格证、2年以上经验',
        '福利': '五险一金、带薪年假、员工健身',
        '工作时间': '做六休一，9:00-21:00',
      },
      images: ['img1', 'img2'],
    },
    {
      id: 32,
      title: '羽毛球陪练招募',
      description: '周末兼职，要求有羽毛球教学经验。羽毛球馆周末陪练，主要服务初级和中级学员，按小时计费，时间灵活。',
      category: '兼职',
      location: '福田区',
      time: '4小时前',
      imageStyle: 5,
      type: 'job',
      price: '100-150/小时',
      publisher: {
        name: '飞扬羽毛球馆',
        wechat: 'feiyang_badminton',
      },
      details: {
        '岗位': '羽毛球陪练',
        '工作类型': '兼职',
        '薪资': '100-150元/小时',
        '要求': '羽毛球教学经验、有耐心',
        '工作时间': '周末，时间灵活',
      },
      images: ['img1'],
    },
    {
      id: 33,
      title: '游泳馆前台接待',
      description: '工作时间灵活，待遇优厚，包吃住。负责会员接待、咨询、办卡等工作，要求形象好、沟通能力强。',
      category: '全职',
      location: '宝安区',
      time: '6小时前',
      imageStyle: 0,
      type: 'job',
      price: '5000-7000',
      publisher: {
        name: '碧海游泳馆',
        wechat: 'bihai_pool_hr',
        phone: '0755-6666****',
      },
      details: {
        '岗位': '前台接待',
        '工作类型': '全职',
        '薪资': '5000-7000元/月',
        '要求': '形象好、沟通能力强',
        '福利': '包吃住、五险',
        '工作时间': '做六休一',
      },
      images: ['img1'],
    },
  ],
}
